### ISSUE TITLE
docker logs shows always Couldn't bind socket: Permission denied

### ISSUE THREAD

**Issue by elschman** [konstruktoid/AptCacherNG_Build#5]
Couldn't bind socket: Permission denied
looks like something missing.

and may there is a way to provide a working ancg.conf from outside ..

which ancg version and linux version is executed inside ?

**Comment by konstruktoid** [comment]
Hi @elschman and thanks for reporting this.
I've updated the Dockerfile and everything should work as expected now.

You can use volumes to serve a local ancg.conf to the container.

The current version is Debian Apt-Cacher-NG/3.3.1, the container uses the available Focal package (https://packages.ubuntu.com/focal/apt-cacher-ng).
